[project]
name = "data-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["fastmcp>=2.11.2", "hyperleda", "mcp[cli]>=1.9.3"]

[tool.uv.sources]
hyperleda = { git = "https://github.com/HyperLEDA/client.git" }
